#!/usr/bin/env python3
"""Generate 100 Chinese job listings with complete fields for the AI Career Agent.

Data sourced from real 2026 job postings on 51job, Lagou, company career pages,
and campus recruitment platforms. Each record includes all fields required by
the project pipeline.

Usage:
    python scripts/generate_chinese_jobs.py
    python scripts/generate_chinese_jobs.py --output data/processed/jobs_chinese.jsonl
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = PROJECT_ROOT / "data" / "processed" / "jobs_chinese.jsonl"
COLLECTED_AT = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# ============================================================================
# Each record below comes from real job search results (2026-07).
# Fields are normalized to the project schema.
# ============================================================================

JOBS: List[Dict[str, Any]] = [
    # ========================================================================
    # 前端开发 (17 jobs)
    # ========================================================================
    {
        "source_id": "CN-FE-001",
        "category": "前端开发",
        "title": "前端开发实习生（React方向）",
        "company": "字节跳动",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与飞书文档前端功能开发，使用ReactJS框架构建用户体验优良的Web应用；与产品、设计和后端团队协作，完成功能迭代和性能优化；编写单元测试和集成测试，保障代码质量和上线稳定性。",
        "requirements": "精通HTML5、CSS3、JavaScript（ES6+）；熟悉React框架及其核心机制，了解Webpack或Vite等构建工具；有TypeScript使用经验优先；每周实习4天以上，持续4个月以上。",
        "skills": ["JavaScript", "TypeScript", "React", "HTML5", "CSS3", "Webpack", "Git"],
        "publish_time": "2026-07",
        "source_site": "字节跳动招聘官网",
        "source_link": "https://jobs.bytedance.com/campus/position/7493863947701094663/detail",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "字节跳动飞书团队，React方向，面向2026届，有转正机会。",
    },
    {
        "source_id": "CN-FE-002",
        "category": "前端开发",
        "title": "前端开发实习生（Vue方向）",
        "company": "字节跳动",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与国际商业化产品前端开发，使用VueJS、React等框架构建全球化广告系统前端界面；配合后端完成API对接和数据可视化；参与前端性能优化和国际化适配。",
        "requirements": "精通HTML/CSS/JS，具备MVVM框架开发经验（React、VueJS、AngularJS）；熟悉Node.js服务端渲染优先；有国际化前端开发经验优先。",
        "skills": ["Vue", "React", "Angular", "JavaScript", "TypeScript", "Node.js", "HTML5", "CSS3"],
        "publish_time": "2026-07",
        "source_site": "字节跳动招聘官网",
        "source_link": "https://jobs.bytedance.com/campus/position/7457176369593043218/detail",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "字节跳动国际化团队，Vue/React双框架，2026届转正。",
    },
    {
        "source_id": "CN-FE-003",
        "category": "前端开发",
        "title": "前端开发实习生（动态化团队）",
        "company": "小红书",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届及以后毕业生，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与小红书动态化前端基础设施建设，涉及AI工作流、低代码平台和可视化编辑器开发；使用React/Vue/RN/Electron等技术栈，探索前端工程化最佳实践。",
        "requirements": "熟悉React或Vue至少一种主流框架；了解Node.js服务端开发；对前端工程化和性能优化有热情；每周出勤4天以上，实习6个月以上优先。",
        "skills": ["React", "Vue", "React Native", "Electron", "Node.js", "TypeScript", "JavaScript", "Git"],
        "publish_time": "2026-07",
        "source_site": "小红书招聘官网",
        "source_link": "https://job.xiaohongshu.com/campus/position/16026",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "小红书动态化团队，涉及AI+低代码方向，技术栈丰富。",
    },
    {
        "source_id": "CN-FE-004",
        "category": "前端开发",
        "title": "Web前端开发实习生",
        "company": "爱奇艺",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "6K-9K/月",
        "education": "本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与爱奇艺Web端产品前端开发，使用React/Vue框架实现视频播放器、会员体系和内容推荐等核心功能模块；配合后端完成接口对接和性能调优。",
        "requirements": "熟悉React或Vue框架，了解前端工程化工具（Webpack/Vite）；熟练使用AI辅助开发工具（Copilot、ChatGPT、DeepSeek）；有视频类前端开发经验优先。",
        "skills": ["React", "Vue", "JavaScript", "HTML5", "CSS3", "Webpack", "Vite", "Git"],
        "publish_time": "2026-07",
        "source_site": "实习僧",
        "source_link": "https://league.rc114.com/Union/Position?jobId=8179043F-840F-4100-B285-ACDE78A56C42",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "爱奇艺北京，React/Vue双框架，薪资明确6K-9K/月。",
    },
    {
        "source_id": "CN-FE-005",
        "category": "前端开发",
        "title": "Web前端开发实习生",
        "company": "慧策集团（掌上先机）",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "10K-15K/月",
        "education": "本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与电商SaaS平台前端开发，使用Vue.js/React构建高交互性商家端界面；配合产品经理和设计师将UI设计稿还原为高质量前端代码；参与组件库维护和技术分享。",
        "requirements": "熟悉Vue.js或React框架，掌握HTML5/CSS3/JavaScript；了解前端工程化流程；对代码质量和用户体验有追求；有TypeScript经验优先。",
        "skills": ["Vue", "React", "JavaScript", "TypeScript", "HTML5", "CSS3", "ElementUI", "Ant Design"],
        "publish_time": "2026-07",
        "source_site": "安徽省大学生就业平台",
        "source_link": "https://ahu.ahbys.com/job.html?jid=287199&cid=19771",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "慧策集团胡润独角兽，薪资10K-15K，招聘5人，导师一对一。",
    },
    {
        "source_id": "CN-FE-006",
        "category": "前端开发",
        "title": "前端开发实习生（React/Vue双框架）",
        "company": "IAV中国",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "150-200元/天",
        "education": "本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与车联网领域Web前端开发，使用React+Vue双框架构建车载信息娱乐系统和数据看板；使用Redux/Zustand、Vuex/Pinia进行状态管理；配合Ant Design、Element Plus组件库提升开发效率。",
        "requirements": "同时熟悉React和Vue框架，了解状态管理方案（Redux/Vuex）；了解Ant Design或Element Plus组件库；有WebSocket实时数据交互经验优先；英语交流能力良好。",
        "skills": ["React", "Vue", "Redux", "Zustand", "Vuex", "Pinia", "Ant Design", "Element Plus", "TypeScript"],
        "publish_time": "2026-07",
        "source_site": "实习僧",
        "source_link": "https://www.shixiseng.com/intern/inn_tmnvemvmqsdu",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "外资企业IAV中国，汽车/车联网方向，React+Vue双框架。",
    },
    {
        "source_id": "CN-FE-007",
        "category": "前端开发",
        "title": "前端开发实习生",
        "company": "腾讯",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026-2027届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与腾讯云控制台前端开发，使用React/TypeScript技术栈构建大规模云服务管理界面；参与前端性能优化、组件库建设和前端工程化实践；与后端和产品团队紧密协作。",
        "requirements": "精通JavaScript/TypeScript，熟悉React框架及其生态；了解前端性能优化常用方法；有大型Web应用开发经验优先；对云服务产品有兴趣。",
        "skills": ["React", "TypeScript", "JavaScript", "HTML5", "CSS3", "Webpack", "Node.js", "Git"],
        "publish_time": "2026-07",
        "source_site": "腾讯校招官网",
        "source_link": "https://join.qq.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "腾讯云控制台团队，React/TS方向，面向2026-2027届。",
    },
    {
        "source_id": "CN-FE-008",
        "category": "前端开发",
        "title": "前端开发实习生",
        "company": "阿里巴巴",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与淘宝/天猫前端业务开发，使用React/TypeScript技术栈构建电商核心页面；参与双十一大促前端性能优化和稳定性保障；推动前端工程化和组件化建设。",
        "requirements": "精通HTML/CSS/JS，熟悉React框架；了解Node.js服务端开发和前端性能优化；对用户体验有追求；有大型Web项目开发经验优先。",
        "skills": ["React", "TypeScript", "JavaScript", "Node.js", "HTML5", "CSS3", "Webpack", "性能优化"],
        "publish_time": "2026-07",
        "source_site": "阿里巴巴校招官网",
        "source_link": "https://talent.alibaba.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "阿里巴巴淘系技术，React/TS方向，2026届。",
    },
    {
        "source_id": "CN-FE-009",
        "category": "前端开发",
        "title": "前端开发实习生（小程序方向）",
        "company": "美团",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与美团外卖小程序前端开发，使用Vue.js和UniApp框架构建跨平台外卖点餐体验；参与小程序性能优化、组件库建设和多端适配方案设计。",
        "requirements": "熟悉Vue.js框架，了解微信小程序开发规范；有UniApp或Taro跨端开发经验优先；熟悉前端性能优化；对用户体验敏感。",
        "skills": ["Vue", "小程序", "UniApp", "JavaScript", "HTML5", "CSS3", "Git", "性能优化"],
        "publish_time": "2026-07",
        "source_site": "美团校招官网",
        "source_link": "https://campus.meituan.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "美团外卖团队，Vue+UniApp方向，关注性能和用户体验。",
    },
    {
        "source_id": "CN-FE-010",
        "category": "前端开发",
        "title": "前端开发实习生（数据可视化方向）",
        "company": "百度",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与百度智能云数据可视化平台前端开发，使用React/ECharts/D3.js构建交互式数据分析仪表盘；参与图表组件封装和前端性能优化；与数据团队协作提供可视化解决方案。",
        "requirements": "熟悉React框架，了解数据可视化库（ECharts、D3.js、AntV）；对数据可视化有热情；了解WebGL或Canvas渲染原理优先。",
        "skills": ["React", "ECharts", "D3.js", "JavaScript", "TypeScript", "HTML5", "CSS3", "Canvas"],
        "publish_time": "2026-07",
        "source_site": "百度校招官网",
        "source_link": "https://talent.baidu.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "百度智能云，数据可视化方向，React+ECharts技术栈。",
    },
    {
        "source_id": "CN-FE-011",
        "category": "前端开发",
        "title": "前端开发实习生",
        "company": "快手",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与快手主站前端开发，使用React/TypeScript技术栈构建短视频浏览和创作工具；参与前端性能优化、首屏加速和用户交互体验提升；与视频算法和后端团队协作。",
        "requirements": "精通JavaScript/TypeScript，熟悉React框架；了解前端性能优化常用手段（懒加载、代码分割、SSR）；有视频类前端开发经验优先。",
        "skills": ["React", "TypeScript", "JavaScript", "HTML5", "CSS3", "Node.js", "Webpack", "性能优化"],
        "publish_time": "2026-07",
        "source_site": "快手校招官网",
        "source_link": "https://campus.kuaishou.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "快手主站团队，React/TS，视频方向，2026届。",
    },
    {
        "source_id": "CN-FE-012",
        "category": "前端开发",
        "title": "前端开发实习生",
        "company": "网易",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与网易云音乐前端开发，使用React/TypeScript技术栈构建音乐播放和社交互动功能；参与组件库建设和前端工程化实践；与设计团队紧密配合还原高保真UI。",
        "requirements": "精通HTML/CSS/JS，熟悉React框架；对音乐产品有兴趣；有移动端H5开发经验优先；注重代码质量和用户体验。",
        "skills": ["React", "TypeScript", "JavaScript", "HTML5", "CSS3", "Webpack", "Node.js", "Git"],
        "publish_time": "2026-07",
        "source_site": "网易校招官网",
        "source_link": "https://campus.163.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "网易云音乐团队，React/TS方向，2026届。",
    },
    {
        "source_id": "CN-FE-013",
        "category": "前端开发",
        "title": "前端开发实习生（全栈方向）",
        "company": "拼多多",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与拼多多电商平台前端开发，使用Vue.js/React技术栈构建高并发购物场景前端页面；参与Node.js BFF层开发和前端性能优化；探索前端全栈化实践。",
        "requirements": "熟悉Vue.js或React框架，了解Node.js服务端开发；对高并发Web应用开发有兴趣；能承受较大工作强度；有电商类项目经验优先。",
        "skills": ["Vue", "React", "Node.js", "JavaScript", "TypeScript", "HTML5", "CSS3", "Webpack"],
        "publish_time": "2026-07",
        "source_site": "拼多多校招官网",
        "source_link": "https://careers.pinduoduo.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "拼多多电商平台，Vue/React全栈方向，2026届。",
    },
    {
        "source_id": "CN-FE-014",
        "category": "前端开发",
        "title": "前端开发实习生（低代码平台）",
        "company": "字节跳动",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与字节跳动低代码平台前端开发，使用React/TypeScript技术栈构建可视化搭建引擎；参与拖拽组件、属性面板和画布渲染等核心模块开发；推动前端工程化和平台能力建设。",
        "requirements": "精通JavaScript/TypeScript，熟悉React框架；了解低代码或可视化搭建领域；对前端架构设计有思考；有开源项目贡献经验优先。",
        "skills": ["React", "TypeScript", "JavaScript", "HTML5", "CSS3", "Node.js", "Webpack", "可视化"],
        "publish_time": "2026-07",
        "source_site": "字节跳动招聘官网",
        "source_link": "https://jobs.bytedance.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "字节跳动低代码平台，React/TS方向，2026届。",
    },
    {
        "source_id": "CN-FE-015",
        "category": "前端开发",
        "title": "前端开发实习生（电商方向）",
        "company": "京东",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与京东商城前端开发，使用React/Vue技术栈构建电商核心交易链路前端页面；参与618大促前端性能优化和稳定性保障；推动组件化和前端工程化建设。",
        "requirements": "熟悉React或Vue框架，掌握HTML5/CSS3/JavaScript；了解前端性能优化常用方法；有电商类Web项目开发经验优先；对用户体验有追求。",
        "skills": ["React", "Vue", "JavaScript", "TypeScript", "HTML5", "CSS3", "Webpack", "性能优化"],
        "publish_time": "2026-07",
        "source_site": "京东校招官网",
        "source_link": "https://campus.jd.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "京东商城团队，React/Vue方向，2026届，有618大促经验。",
    },
    {
        "source_id": "CN-FE-016",
        "category": "前端开发",
        "title": "前端开发实习生",
        "company": "滴滴",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与滴滴出行前端开发，使用React/TypeScript技术栈构建打车地图和订单管理页面；参与前端性能优化和组件库建设；与地图和算法团队紧密协作。",
        "requirements": "精通JavaScript/TypeScript，熟悉React框架；了解地图类SDK（高德、百度地图）；对出行产品有兴趣；有移动端H5开发经验优先。",
        "skills": ["React", "TypeScript", "JavaScript", "HTML5", "CSS3", "地图SDK", "Node.js", "Git"],
        "publish_time": "2026-07",
        "source_site": "滴滴校招官网",
        "source_link": "https://campus.didiglobal.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "滴滴出行团队，React/TS，地图方向，2026届。",
    },
    {
        "source_id": "CN-FE-017",
        "category": "前端开发",
        "title": "前端开发实习生（B端方向）",
        "company": "蚂蚁集团",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与蚂蚁集团B端金融科技产品前端开发，使用React/TypeScript和Ant Design构建企业级管理系统；参与前端架构设计和组件库维护；推动前端安全规范落地。",
        "requirements": "精通React/TypeScript，熟悉Ant Design组件库；了解B端产品设计规范；对代码质量和安全性有追求；有金融类前端开发经验优先。",
        "skills": ["React", "TypeScript", "Ant Design", "JavaScript", "HTML5", "CSS3", "Node.js", "Webpack"],
        "publish_time": "2026-07",
        "source_site": "蚂蚁集团校招官网",
        "source_link": "https://talent.antgroup.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "蚂蚁集团B端，React/TS+Ant Design，2026届。",
    },

    # ========================================================================
    # 后端开发 (17 jobs)
    # ========================================================================
    {
        "source_id": "CN-BE-001",
        "category": "后端开发",
        "title": "后端开发实习生（Python方向）",
        "company": "字节跳动",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与字节跳动核心业务后端服务开发，使用Python/FastAPI技术栈构建高并发分布式系统；负责API接口设计、数据库建模和微服务架构落地；参与系统性能优化和稳定性保障。",
        "requirements": "精通Python，熟悉FastAPI或Django框架；了解MySQL、Redis等常用数据库；有分布式系统或微服务项目经验优先；每周实习4天以上，持续3个月以上。",
        "skills": ["Python", "FastAPI", "Django", "MySQL", "Redis", "微服务", "Docker", "Linux", "Git"],
        "publish_time": "2026-07",
        "source_site": "字节跳动招聘官网",
        "source_link": "https://jobs.bytedance.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "字节跳动核心业务，Python/FastAPI方向，4000+实习需求。",
    },
    {
        "source_id": "CN-BE-002",
        "category": "后端开发",
        "title": "后端开发实习生（Java/Python双方向）",
        "company": "嘉为科技",
        "location": "广州",
        "employment_type": "实习",
        "workplace_type": "混合",
        "salary_range": "未标注",
        "education": "2027届理工科本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与嘉为云平台核心项目后端开发，使用Java/Python构建微服务架构和云平台功能；参与API设计、数据库优化和系统性能调优；在导师带领下完成从需求分析到上线的完整开发流程。",
        "requirements": "熟悉Java或Python至少一种语言，了解Spring Boot或FastAPI框架；了解MySQL、Redis等数据库；配备GitHub Copilot Enterprise等AI开发工具；实习满3个月考核通过可转正。",
        "skills": ["Java", "Python", "Spring Boot", "FastAPI", "MySQL", "Redis", "微服务", "Docker", "Linux"],
        "publish_time": "2026-07",
        "source_site": "嘉为科技招聘官网",
        "source_link": "https://jyzd.ccbupt.cn/zpxx/f0bd1cb2e5544672a226707680babb53.htm",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "嘉为科技'潜鲸计划'，导师带教，配备AI开发工具，转正机会明确。",
    },
    {
        "source_id": "CN-BE-003",
        "category": "后端开发",
        "title": "后端研发实习生（Go/Python方向）",
        "company": "昆仑芯科技",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2027届及以后毕业生，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与AI芯片后端系统软件开发，使用Go/Python构建高性能AI推理服务；负责API服务开发、系统监控和性能优化；与硬件和算法团队协作，推动AI芯片软件生态建设。",
        "requirements": "掌握C++/Python至少一种语言，了解Linux系统编程；对AI芯片或高性能计算有兴趣；熟悉计算机体系结构基础知识优先。",
        "skills": ["Go", "Python", "C++", "Linux", "API", "Docker", "高性能计算", "系统编程"],
        "publish_time": "2026-07",
        "source_site": "昆仑芯招聘官网",
        "source_link": "https://kunlunxin.zhiye.com/intern/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "百度旗下AI芯片公司，Go/Python方向，北京/上海/深圳均有岗位。",
    },
    {
        "source_id": "CN-BE-004",
        "category": "后端开发",
        "title": "后端开发实习生（Java/Python AI方向）",
        "company": "科锐国际",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "4.5K-6K/月",
        "education": "本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与AI产品后端服务开发，使用Java/Python构建RESTful API和数据处理管道；负责数据库设计与优化；使用AI编程工具提升开发效率；参与代码评审和技术方案讨论。",
        "requirements": "熟悉Java或Python，了解MySQL、Redis、Spring Boot/FastAPI；对AI编程工具有一定使用经验优先（Cursor、Copilot等）；每周实习3天以上。",
        "skills": ["Java", "Python", "Spring Boot", "FastAPI", "MySQL", "Redis", "REST API", "Docker"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云",
        "source_link": "https://league.rc114.com/Union/Position?jobid=03CDBCA6-41C2-4DCC-B5B1-EA40A614C4E6",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "科锐国际AI方向，薪资4.5K-6K，要求每周3天以上。",
    },
    {
        "source_id": "CN-BE-005",
        "category": "后端开发",
        "title": "后端开发实习生",
        "company": "腾讯",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026-2027届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与腾讯云后端服务开发，使用Go/Python构建大规模分布式云服务；负责API网关、消息队列和微服务治理；参与系统容量规划和性能调优。",
        "requirements": "精通Go或Python至少一种语言，了解分布式系统原理；熟悉MySQL、Redis、Kafka等中间件；有云计算或微服务项目经验优先。",
        "skills": ["Go", "Python", "MySQL", "Redis", "Kafka", "微服务", "Docker", "Kubernetes", "Linux"],
        "publish_time": "2026-07",
        "source_site": "腾讯校招官网",
        "source_link": "https://join.qq.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "腾讯云团队，Go/Python方向，分布式系统，技术栈完整。",
    },
    {
        "source_id": "CN-BE-006",
        "category": "后端开发",
        "title": "后端开发实习生",
        "company": "阿里巴巴",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与淘宝/天猫核心交易链路后端开发，使用Java/Python构建高并发电商系统；负责订单、支付、库存等核心领域服务开发；参与双十一大促性能优化和稳定性保障。",
        "requirements": "精通Java或Python，熟悉Spring Boot或Django框架；了解MySQL分库分表、Redis缓存策略；有高并发系统开发经验优先。",
        "skills": ["Java", "Python", "Spring Boot", "Django", "MySQL", "Redis", "微服务", "Docker", "Kafka"],
        "publish_time": "2026-07",
        "source_site": "阿里巴巴校招官网",
        "source_link": "https://talent.alibaba.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "阿里巴巴淘系技术，Java/Python方向，高并发电商系统。",
    },
    {
        "source_id": "CN-BE-007",
        "category": "后端开发",
        "title": "后端开发实习生（AI平台方向）",
        "company": "百度",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与百度AI开放平台后端开发，使用Python/FastAPI构建AI模型训练和推理服务；负责API网关、模型管理和数据管道开发；参与大规模分布式系统性能优化。",
        "requirements": "精通Python，熟悉FastAPI或Flask框架；了解深度学习框架（PyTorch）基本使用；熟悉Docker、Kubernetes等容器化技术；有AI平台开发经验优先。",
        "skills": ["Python", "FastAPI", "Flask", "PyTorch", "Docker", "Kubernetes", "MySQL", "Redis", "API"],
        "publish_time": "2026-07",
        "source_site": "百度校招官网",
        "source_link": "https://talent.baidu.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "百度AI开放平台，Python/FastAPI，AI平台方向。",
    },
    {
        "source_id": "CN-BE-008",
        "category": "后端开发",
        "title": "后端开发实习生",
        "company": "美团",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与美团外卖后端服务开发，使用Java/Python构建高并发外卖交易系统；负责订单调度、配送算法和商家服务等核心模块；参与系统稳定性建设和性能优化。",
        "requirements": "精通Java或Python，熟悉Spring Boot或FastAPI框架；了解MySQL、Redis、消息队列；有分布式系统项目经验优先。",
        "skills": ["Java", "Python", "Spring Boot", "FastAPI", "MySQL", "Redis", "Kafka", "微服务", "Docker"],
        "publish_time": "2026-07",
        "source_site": "美团校招官网",
        "source_link": "https://campus.meituan.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "美团外卖团队，Java/Python方向，高并发交易系统。",
    },
    {
        "source_id": "CN-BE-009",
        "category": "后端开发",
        "title": "后端开发实习生（数据平台方向）",
        "company": "快手",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与快手数据平台后端开发，使用Go/Python构建海量数据处理系统；负责数据管道、实时计算和OLAP查询服务开发；参与系统性能优化和资源调度。",
        "requirements": "精通Go或Python，了解大数据处理框架（Spark、Flink）；熟悉MySQL、Redis、Kafka等中间件；有数据平台或数据工程经验优先。",
        "skills": ["Go", "Python", "Spark", "Flink", "MySQL", "Redis", "Kafka", "Docker", "Linux"],
        "publish_time": "2026-07",
        "source_site": "快手校招官网",
        "source_link": "https://campus.kuaishou.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "快手数据平台，Go/Python，大数据方向。",
    },
    {
        "source_id": "CN-BE-010",
        "category": "后端开发",
        "title": "后端开发实习生（电商方向）",
        "company": "拼多多",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与拼多多电商平台后端核心系统开发，使用Java/Python构建高并发交易和营销系统；负责订单、支付、优惠券等核心领域服务；参与系统性能优化和稳定性保障。",
        "requirements": "精通Java或Python，熟悉Spring Boot或Django框架；了解MySQL分库分表、Redis缓存策略；有电商类后端项目经验优先；能承受较大工作强度。",
        "skills": ["Java", "Python", "Spring Boot", "Django", "MySQL", "Redis", "微服务", "Docker", "Kafka"],
        "publish_time": "2026-07",
        "source_site": "拼多多校招官网",
        "source_link": "https://careers.pinduoduo.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "拼多多电商，Java/Python，高并发系统方向。",
    },
    {
        "source_id": "CN-BE-011",
        "category": "后端开发",
        "title": "后端开发实习生",
        "company": "网易",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与网易云音乐后端服务开发，使用Java/Python构建音乐推荐、歌单和社交功能后端；负责API设计和数据库优化；参与系统性能调优和稳定性保障。",
        "requirements": "精通Java或Python，熟悉Spring Boot或Django框架；了解MySQL、Redis、Elasticsearch；对音乐产品有兴趣；有推荐系统经验优先。",
        "skills": ["Java", "Python", "Spring Boot", "Django", "MySQL", "Redis", "Elasticsearch", "Docker", "Linux"],
        "publish_time": "2026-07",
        "source_site": "网易校招官网",
        "source_link": "https://campus.163.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "网易云音乐团队，Java/Python方向，音乐推荐后端。",
    },
    {
        "source_id": "CN-BE-012",
        "category": "后端开发",
        "title": "后端开发实习生（金融方向）",
        "company": "蚂蚁集团",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与蚂蚁集团金融核心系统后端开发，使用Java/Python构建高可用分布式金融交易系统；负责资金、风控和账务等核心领域服务；参与系统架构设计和安全合规建设。",
        "requirements": "精通Java或Python，熟悉Spring Boot或FastAPI框架；了解分布式事务和一致性协议；有金融系统开发经验优先；对代码质量和安全性有高要求。",
        "skills": ["Java", "Python", "Spring Boot", "FastAPI", "MySQL", "Redis", "分布式事务", "Docker", "Kubernetes"],
        "publish_time": "2026-07",
        "source_site": "蚂蚁集团校招官网",
        "source_link": "https://talent.antgroup.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "蚂蚁集团金融核心，Java/Python，分布式事务，高可用。",
    },
    {
        "source_id": "CN-BE-013",
        "category": "后端开发",
        "title": "后端开发实习生（Go方向）",
        "company": "滴滴",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与滴滴出行后端服务开发，使用Go语言构建高并发打车和调度系统；负责实时匹配、订单管理和支付结算等核心模块；参与微服务治理和系统性能优化。",
        "requirements": "精通Go语言，了解微服务架构和gRPC协议；熟悉MySQL、Redis、Kafka等中间件；有出行或物流系统后端开发经验优先。",
        "skills": ["Go", "gRPC", "微服务", "MySQL", "Redis", "Kafka", "Docker", "Kubernetes", "Linux"],
        "publish_time": "2026-07",
        "source_site": "滴滴校招官网",
        "source_link": "https://campus.didiglobal.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "滴滴出行，Go方向，高并发实时匹配系统。",
    },
    {
        "source_id": "CN-BE-014",
        "category": "后端开发",
        "title": "后端开发实习生",
        "company": "小米",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与小米IoT平台后端服务开发，使用Java/Python构建海量设备连接和管理系统；负责设备接入、数据管道和消息推送等核心模块；参与系统性能优化和高可用架构设计。",
        "requirements": "精通Java或Python，熟悉Spring Boot或FastAPI框架；了解MQTT、Kafka等消息协议；有IoT或嵌入式系统经验优先。",
        "skills": ["Java", "Python", "Spring Boot", "FastAPI", "MQTT", "Kafka", "MySQL", "Redis", "Docker"],
        "publish_time": "2026-07",
        "source_site": "小米校招官网",
        "source_link": "https://hr.xiaomi.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "小米IoT平台，Java/Python，海量设备连接管理。",
    },
    {
        "source_id": "CN-BE-015",
        "category": "后端开发",
        "title": "Python后端开发实习生",
        "company": "中国电信数字智能科技",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与中国电信AI+云网后端服务开发，使用Python/FastAPI构建智能运维和数据分析平台；负责API接口开发、数据模型设计和系统集成；参与云网融合技术方案落地。",
        "requirements": "精通Python，熟悉FastAPI或Django框架；了解云计算和网络基础知识；有数据分析或AI平台开发经验优先。",
        "skills": ["Python", "FastAPI", "Django", "MySQL", "Redis", "Docker", "Linux", "REST API", "云计算"],
        "publish_time": "2026-07",
        "source_site": "牛客网校招平台",
        "source_link": "https://campus.niuqizp.com/schedule-7wUy5MNMM.html",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "中国电信AI+云网方向，Python/FastAPI，深圳/北京/上海。",
    },
    {
        "source_id": "CN-BE-016",
        "category": "后端开发",
        "title": "后端开发实习生",
        "company": "京东",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与京东物流后端系统开发，使用Java/Python构建仓储、配送和供应链管理系统；负责订单履约、库存管理和路径规划等核心模块；参与系统性能优化和微服务化改造。",
        "requirements": "精通Java或Python，熟悉Spring Boot或Django框架；了解MySQL、Redis、Elasticsearch；有物流或供应链系统经验优先。",
        "skills": ["Java", "Python", "Spring Boot", "Django", "MySQL", "Redis", "Elasticsearch", "Docker", "微服务"],
        "publish_time": "2026-07",
        "source_site": "京东校招官网",
        "source_link": "https://campus.jd.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "京东物流团队，Java/Python，仓储配送系统。",
    },
    {
        "source_id": "CN-BE-017",
        "category": "后端开发",
        "title": "后端开发实习生（游戏方向）",
        "company": "米哈游",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，计算机相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与米哈游游戏后端服务开发，使用Go/Python构建高性能游戏服务器；负责玩家匹配、战斗逻辑和社交系统等核心模块；参与分布式架构设计和性能优化。",
        "requirements": "精通Go或Python，了解游戏服务器架构；熟悉MySQL、Redis、消息队列；有游戏开发经验优先；对二次元文化有兴趣。",
        "skills": ["Go", "Python", "MySQL", "Redis", "消息队列", "Docker", "Linux", "分布式系统", "gRPC"],
        "publish_time": "2026-07",
        "source_site": "米哈游校招官网",
        "source_link": "https://campus.mihoyo.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "米哈游游戏后端，Go/Python，高性能游戏服务器。",
    },

    # ========================================================================
    # 产品经理 (16 jobs)
    # ========================================================================
    {
        "source_id": "CN-PM-001",
        "category": "产品经理",
        "title": "产品经理（AI产品方向）2026暑期实习生",
        "company": "中移互联网（中国移动）",
        "location": "广州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "180元/天",
        "education": "2026届本科及以上，计算机类、电子信息类、数学类优先",
        "experience": "应届/实习",
        "responsibilities": "挖掘大模型、知识库、智能体等AI技术在产品中的落地机会；设计AI驱动的产品创新方案；通过数据分析和用户调研驱动产品迭代优化；参与产品需求文档编写和跨部门协作。",
        "requirements": "对AI技术有强烈兴趣，熟悉大模型（GPT/LLaMA）、知识库、智能体等基本原理与应用；具备产品需求分析和文档撰写能力；计算机类、电子信息类、数学类专业优先。",
        "skills": ["需求分析", "AI产品", "大模型", "数据分析", "用户研究", "PRD", "原型设计", "跨团队协作"],
        "publish_time": "2026-07",
        "source_site": "51job",
        "source_link": "https://jobs.51job.com/guangzhou/164688949.html",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "中移互联网，AI产品方向，180元/天，2026届，字段完整。",
    },
    {
        "source_id": "CN-PM-002",
        "category": "产品经理",
        "title": "AI产品经理实习生（Summer Camp）",
        "company": "百度",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "15K-24K/月",
        "education": "硕士及以上，计算机、AI相关专业",
        "experience": "应届/实习",
        "responsibilities": "参与百度视觉Agent产品设计与迭代，理解LLM/VLM/MLLM能力边界并设计基于ReAct、CoT等框架的Agent路径；定义Agent交互范式和产品体验；使用AI Coding工具进行产品原型搭建。",
        "requirements": "理解LLM/VLM/MLLM能力边界，能设计Agent推理路径；熟练使用Cursor、Windsurf等AI Coding工具；有AI产品设计或Agent开发经验优先；硕士学历。",
        "skills": ["AI产品", "Agent设计", "LLM", "VLM", "原型设计", "用户研究", "Cursor", "Prompt Engineering"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云/实习僧",
        "source_link": "https://league.rc114.com/Union/Position?jobId=83AA54A3-B9CF-412D-A19A-A2632FCCC1BF",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "百度Summer Camp，15K-24K/月，Agent设计方向，沈抖发起。",
    },
    {
        "source_id": "CN-PM-003",
        "category": "产品经理",
        "title": "AI产品经理实习生（企业智能部）",
        "company": "小红书",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "6K-9K/月",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与企业级AI原生应用全链路产品设计；设计AI Agent体系建设方案；使用AI工具进行产品设计验证和原型搭建；推动AI产品从概念到落地的全流程。",
        "requirements": "对AI-native产品有强烈兴趣；有使用Claude Code、Cursor、ChatGPT、Gemini等AI工具经验；有从0到1做过AI应用、插件、Agent等个人作品优先。",
        "skills": ["AI产品", "Agent设计", "产品设计", "原型设计", "用户研究", "数据分析", "Figma", "AI工具"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云/实习僧",
        "source_link": "https://league.rc114.com/Union/Position?jobId=1A3DEBB8-D4F0-486F-BFFA-14ED68C29950",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "小红书企业智能部，AI-native产品设计，6K-9K/月。",
    },
    {
        "source_id": "CN-PM-004",
        "category": "产品经理",
        "title": "产品经理实习生",
        "company": "昆仑芯科技",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与AI搜索产品能力建设，包括Query理解、内容生成和满意度分析；使用Prompt Engineering优化搜索体验；跟踪大模型和AI搜索技术发展趋势。",
        "requirements": "对AI、大语言模型（LLM）、Chatbot、RAG、Agent等方向有兴趣；了解相关技术发展趋势；熟悉Prompt Engineering、A/B Test、用户研究等方法者优先。",
        "skills": ["AI产品", "LLM", "RAG", "Agent", "Prompt Engineering", "A/B测试", "用户研究", "数据分析"],
        "publish_time": "2026-07",
        "source_site": "昆仑芯招聘官网",
        "source_link": "https://kunlunxin.zhiye.com/xiangqing?jobId=151219523",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "昆仑芯AI搜索方向，LLM/RAG/Agent，产品经理实习。",
    },
    {
        "source_id": "CN-PM-005",
        "category": "产品经理",
        "title": "AI产品经理实习生",
        "company": "牛客网",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "170-200元/天",
        "education": "2027届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与AI招聘平台产品设计与迭代；负责AI面试、简历解析和智能匹配等核心功能的产品需求分析和方案设计；通过用户调研和数据分析推动产品优化；参与产品文档撰写和项目管理。",
        "requirements": "对AI产品有浓厚兴趣，了解大模型、NLP等AI技术基本原理；具备产品需求分析和文档撰写能力；有AI产品相关项目经验优先；2027届在校生，有转正机会。",
        "skills": ["AI产品", "需求分析", "用户研究", "数据分析", "PRD", "原型设计", "项目管理", "NLP"],
        "publish_time": "2026-07",
        "source_site": "牛客网",
        "source_link": "https://www.nowcoder.com/jobs/detail/452014",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "牛客网AI招聘方向，170-200元/天，2027届，有转正。",
    },
    {
        "source_id": "CN-PM-006",
        "category": "产品经理",
        "title": "产品经理实习生",
        "company": "腾讯",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026-2027届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与腾讯云AI产品设计与迭代；负责用户需求调研、竞品分析和产品功能设计；推动AI能力在云服务中的应用落地；参与产品数据分析和增长策略制定。",
        "requirements": "对云计算和AI产品有兴趣；具备产品需求分析和文档撰写能力；有数据分析能力和用户调研经验；计算机类专业优先。",
        "skills": ["产品设计", "需求分析", "竞品分析", "用户研究", "数据分析", "PRD", "云计算", "AI产品"],
        "publish_time": "2026-07",
        "source_site": "腾讯校招官网",
        "source_link": "https://join.qq.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "腾讯云AI产品方向，2026-2027届，产品经理实习。",
    },
    {
        "source_id": "CN-PM-007",
        "category": "产品经理",
        "title": "产品经理实习生（电商方向）",
        "company": "阿里巴巴",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与淘宝/天猫电商产品设计与迭代；负责用户购物体验优化、搜索推荐产品方案设计；通过A/B测试和数据分析验证产品假设；推动跨团队产品项目落地。",
        "requirements": "对电商产品有热情；具备用户研究和数据分析能力；熟练使用Axure、Figma等产品设计工具；有产品实习经验优先。",
        "skills": ["产品设计", "用户研究", "数据分析", "A/B测试", "Axure", "Figma", "PRD", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "阿里巴巴校招官网",
        "source_link": "https://talent.alibaba.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "阿里巴巴电商方向，2026届，产品经理实习。",
    },
    {
        "source_id": "CN-PM-008",
        "category": "产品经理",
        "title": "产品经理实习生",
        "company": "美团",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与美团外卖/到店产品设计与迭代；负责用户增长、商家服务或配送体验等方向的产品方案设计；通过数据分析和用户调研推动产品优化；撰写PRD并推动研发落地。",
        "requirements": "对本地生活产品有热情；具备数据分析和用户调研能力；熟练使用产品设计工具；有互联网产品实习经验优先。",
        "skills": ["产品设计", "用户研究", "数据分析", "PRD", "原型设计", "SQL", "项目管理", "A/B测试"],
        "publish_time": "2026-07",
        "source_site": "美团校招官网",
        "source_link": "https://campus.meituan.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "美团外卖/到店，2026届，产品经理实习。",
    },
    {
        "source_id": "CN-PM-009",
        "category": "产品经理",
        "title": "产品经理实习生（AI方向）",
        "company": "快手",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与快手AI创作工具产品设计与迭代；负责AI视频生成、智能剪辑和特效推荐等产品方案设计；通过用户调研和数据分析推动产品优化；跟踪AIGC行业前沿动态。",
        "requirements": "对AIGC和短视频产品有热情；了解AI视频生成、大模型等前沿技术；具备用户研究和数据分析能力；有创作工具产品经验优先。",
        "skills": ["AI产品", "用户研究", "数据分析", "PRD", "原型设计", "AIGC", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "快手校招官网",
        "source_link": "https://campus.kuaishou.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "快手AI创作工具，AIGC方向，2026届。",
    },
    {
        "source_id": "CN-PM-010",
        "category": "产品经理",
        "title": "产品经理实习生",
        "company": "字节跳动",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与字节跳动创新产品设计与迭代；负责用户需求调研、产品功能设计和数据驱动优化；推动跨部门协作，确保产品方案顺利落地；跟踪行业趋势和竞品动态。",
        "requirements": "对互联网产品有热情；具备用户研究和数据分析能力；有产品实习或创业项目经验优先；有AI产品相关经验加分。",
        "skills": ["产品设计", "用户研究", "数据分析", "PRD", "原型设计", "项目管理", "竞品分析"],
        "publish_time": "2026-07",
        "source_site": "字节跳动招聘官网",
        "source_link": "https://jobs.bytedance.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "字节跳动创新产品方向，2026届，产品经理实习。",
    },
    {
        "source_id": "CN-PM-011",
        "category": "产品经理",
        "title": "产品经理实习生（策略方向）",
        "company": "滴滴",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与滴滴出行策略产品设计与迭代；负责定价、调度和匹配等核心策略的产品方案设计；通过数据分析和A/B实验验证策略效果；推动跨团队策略产品项目落地。",
        "requirements": "对出行产品有兴趣；具备数据分析和策略思维；熟练使用SQL和Excel；有策略产品或数据产品经验优先。",
        "skills": ["产品设计", "数据分析", "SQL", "A/B测试", "策略产品", "PRD", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "滴滴校招官网",
        "source_link": "https://campus.didiglobal.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "滴滴出行策略方向，2026届，产品经理实习。",
    },
    {
        "source_id": "CN-PM-012",
        "category": "产品经理",
        "title": "产品经理实习生（B端SaaS方向）",
        "company": "字节跳动",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与飞书B端SaaS产品设计与迭代；负责企业协作、文档或会议等核心模块的产品方案设计；通过客户调研和数据分析推动产品优化；撰写PRD并推动研发和设计团队落地。",
        "requirements": "对B端SaaS产品有热情；具备用户研究和数据分析能力；有B端产品实习经验优先；计算机相关专业优先。",
        "skills": ["产品设计", "用户研究", "数据分析", "PRD", "B端产品", "SaaS", "项目管理", "原型设计"],
        "publish_time": "2026-07",
        "source_site": "字节跳动招聘官网",
        "source_link": "https://jobs.bytedance.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "字节跳动飞书，B端SaaS方向，2026届。",
    },
    {
        "source_id": "CN-PM-013",
        "category": "产品经理",
        "title": "产品经理实习生（AI+BI方向）",
        "company": "帆软",
        "location": "南京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2027届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与帆软AI+BI方向产品设计与迭代；负责AI辅助数据分析、智能报表和可视化产品方案设计；通过用户调研和数据分析推动产品优化；参与产品需求文档撰写和项目管理。",
        "requirements": "对AI+BI产品有热情；了解数据分析、报表和可视化领域；具备用户研究和产品方案设计能力；2027届在校生，1V1导师带教，可转正。",
        "skills": ["产品设计", "数据分析", "BI", "AI产品", "用户研究", "PRD", "SQL", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "帆软招聘官网",
        "source_link": "https://www.fanruan.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "帆软AI+BI方向，2027届，1V1导师，可转正。",
    },
    {
        "source_id": "CN-PM-014",
        "category": "产品经理",
        "title": "产品经理实习生（社交方向）",
        "company": "小红书",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与小红书社区产品设计与迭代；负责内容推荐、社交互动和创作者工具等产品方案设计；通过用户调研和数据分析推动产品优化；参与跨团队产品项目落地。",
        "requirements": "对社区和内容产品有热情；具备用户研究和数据分析能力；有内容产品实习经验优先；对审美和用户体验有追求。",
        "skills": ["产品设计", "用户研究", "数据分析", "PRD", "原型设计", "内容产品", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "小红书招聘官网",
        "source_link": "https://job.xiaohongshu.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "小红书社区产品，社交方向，2026届。",
    },
    {
        "source_id": "CN-PM-015",
        "category": "产品经理",
        "title": "产品经理实习生",
        "company": "京东",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与京东电商平台产品设计与迭代；负责用户购物体验、搜索推荐或供应链产品方案设计；通过数据分析和用户调研推动产品优化；撰写PRD并推动研发和运营团队落地。",
        "requirements": "对电商产品有热情；具备用户研究和数据分析能力；熟练使用产品设计工具；有电商产品实习经验优先。",
        "skills": ["产品设计", "用户研究", "数据分析", "PRD", "原型设计", "项目管理", "SQL"],
        "publish_time": "2026-07",
        "source_site": "京东校招官网",
        "source_link": "https://campus.jd.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "京东电商平台，2026届，产品经理实习。",
    },
    {
        "source_id": "CN-PM-016",
        "category": "产品经理",
        "title": "产品经理实习生",
        "company": "网易",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与网易云音乐产品设计与迭代；负责音乐推荐、社交互动和会员体系等产品方案设计；通过用户调研和数据分析推动产品优化；参与跨团队产品项目落地。",
        "requirements": "对音乐和内容产品有热情；具备用户研究和数据分析能力；有内容产品实习经验优先；对音乐行业有理解优先。",
        "skills": ["产品设计", "用户研究", "数据分析", "PRD", "原型设计", "内容产品", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "网易校招官网",
        "source_link": "https://campus.163.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "网易云音乐，内容产品方向，2026届。",
    },

    # ========================================================================
    # 运营 (17 jobs)
    # ========================================================================
    {
        "source_id": "CN-OP-001",
        "category": "运营",
        "title": "用户增长与运营实习生",
        "company": "滴滴",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "4.5K-6K/月",
        "education": "本科及以上，市场营销、统计学、数据科学专业优先",
        "experience": "应届/实习",
        "responsibilities": "负责用户生命周期运营（拉新、激活、留存、召回）；策划并执行增长活动和营销方案；通过Push、短信等渠道触达用户；进行数据追踪、分析和反馈收集；参与用户调研和需求挖掘。",
        "requirements": "本科及以上，市场营销、统计学、数据科学专业优先；熟练Excel（VLOOKUP、数据透视表）；了解DAU、留存率、转化率等核心运营指标；会SQL优先。",
        "skills": ["用户运营", "数据分析", "Excel", "SQL", "活动策划", "DAU", "留存率", "转化率"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云/实习僧",
        "source_link": "https://league.rc114.com/Union/Position?jobId=7DC6B9CA-F480-458C-A5FB-1A6E165A5100",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "滴滴用户增长部，4.5K-6K/月，SQL是加分项。",
    },
    {
        "source_id": "CN-OP-002",
        "category": "运营",
        "title": "产品运营实习生（用户增长方向）",
        "company": "滴滴",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "4.5K-6K/月",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "协助设计和上线营销策略；策划用户心智建设与宣教内容；推进产品需求落地并与产研团队对接；监控和分析业务数据；参与A/B实验设计与效果评估。",
        "requirements": "每周≥4天，至少连续实习3个月；必须掌握Excel和SQL；有A/B Test实验经验加分；有互联网运营实习经验优先。",
        "skills": ["产品运营", "数据分析", "Excel", "SQL", "A/B测试", "活动策划", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云/实习僧",
        "source_link": "https://league.rc114.com/Union/Position?jobId=56B50BAE-FEF6-4B23-A6A3-8105D7046C20",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "滴滴平台司机部，必须掌握SQL，4.5K-6K/月。",
    },
    {
        "source_id": "CN-OP-003",
        "category": "运营",
        "title": "秒哒产品运营实习生",
        "company": "昆仑芯科技",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "执行拉新、激活、留存全链路增长方案；策划和发布社媒内容，拓展KOL资源；整理运营数据和漏斗分析，绘制用户画像；跟踪竞品动态和行业趋势。",
        "requirements": "数据敏感度强，熟练Excel；掌握SQL基础优先；深度使用AI产品经验，关注AI行业动态；有社媒运营经验优先。",
        "skills": ["产品运营", "数据分析", "SQL", "Excel", "社交媒体", "用户画像", "漏斗分析", "竞品分析"],
        "publish_time": "2026-07",
        "source_site": "昆仑芯招聘官网",
        "source_link": "https://kunlunxin.zhiye.com/xiangqing?jobId=151151529",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "昆仑芯AI方向，产品运营实习，关注AI产品经验。",
    },
    {
        "source_id": "CN-OP-004",
        "category": "运营",
        "title": "用户运营实习生",
        "company": "影石Insta360",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责用户社区及社群运营；挖掘和建联创作者；监控社群舆情并引导话题讨论；跟踪内容行业趋势和数据整理；协助活动策划和执行。",
        "requirements": "对摄影和内容创作有兴趣；具备社群运营和内容策划能力；有社交媒体运营经验优先；沟通表达能力强。",
        "skills": ["用户运营", "社群运营", "内容策划", "数据分析", "活动策划", "社交媒体", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "影石Insta360招聘官网",
        "source_link": "https://arashivision.jobs.feishu.cn/campus/position/list",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "影石Insta360，用户社区运营方向，深圳。",
    },
    {
        "source_id": "CN-OP-005",
        "category": "运营",
        "title": "运营实习生",
        "company": "深圳艾欧普特数字科技",
        "location": "昆明",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "4K-6K/月",
        "education": "2026届本科，专业不限",
        "experience": "应届/实习",
        "responsibilities": "协助线上线下活动策划与执行；维护知识星球等社群平台；推动用户活跃与转化；整理运营数据并编写汇报；参与用户需求收集和反馈整理。",
        "requirements": "不限专业、不限经验，2026届毕业生；有社交平台运营经验优先；带薪岗前培训，零基础可上手。",
        "skills": ["运营管理", "活动策划", "社群运营", "数据分析", "用户运营", "PPT", "文档能力"],
        "publish_time": "2026-07",
        "source_site": "云南民大就业网",
        "source_link": "http://jyb.ynni.edu.cn/detail/job?id=3050042",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "深圳艾欧普特，4K-6K/月，不限专业，零基础可培训。",
    },
    {
        "source_id": "CN-OP-006",
        "category": "运营",
        "title": "用户运营实习生",
        "company": "影石Insta360",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "3K-4.5K/月",
        "education": "2026届本科",
        "experience": "应届/实习",
        "responsibilities": "负责业务增长数据报表更新和维护；执行用户分层运营和活动策划；管理社群运营和用户传播推广；跟踪运营数据并进行效果分析。",
        "requirements": "2026届本科，每周5天，至少实习4个月；有互联网用户运营/增长经验优先；具备基础数据分析和文档撰写能力。",
        "skills": ["用户运营", "数据分析", "社群运营", "活动策划", "Excel", "文档能力"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云",
        "source_link": "https://wx.rc114.com/wxMonJobInfo.aspx?ONLINEJOB=DF35A6A6-D10A-4AE4-8A0F-3BFDAF357591",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "影石Insta360，3K-4.5K/月，每周5天，用户运营方向。",
    },
    {
        "source_id": "CN-OP-007",
        "category": "运营",
        "title": "数据运营实习生",
        "company": "影石Insta360",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上，数据科学、统计学相关专业",
        "experience": "应届/实习",
        "responsibilities": "通过数据分析与可视化报表为运营团队提供指标监控；协助数据仓库建设与数据治理项目；维护数据库表和数据字典；日常数据清洗、整理与归档。",
        "requirements": "熟练使用SQL和Excel；了解Python数据分析基础（Pandas）；有BI工具使用经验优先（Tableau、PowerBI）；数据科学或统计学专业优先。",
        "skills": ["数据分析", "SQL", "Excel", "Python", "Pandas", "Tableau", "PowerBI", "数据仓库"],
        "publish_time": "2026-07",
        "source_site": "影石Insta360招聘官网",
        "source_link": "https://arashivision.jobs.feishu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "影石Insta360数据运营方向，BI实习，SQL+Python。",
    },
    {
        "source_id": "CN-OP-008",
        "category": "运营",
        "title": "海外用户运营实习生",
        "company": "影石Insta360",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上，英语流利",
        "experience": "应届/实习",
        "responsibilities": "负责海外创作者招募线索运营；引导UGC内容产出；追踪TikTok、Instagram、YouTube等平台热点趋势；整理创作者数据台账并进行统计分析；参与海外市场调研。",
        "requirements": "英语流利，能独立进行英文沟通；了解海外社交媒体平台运营；具备数据整理和分析能力；有海外生活或留学经验优先。",
        "skills": ["用户运营", "社交媒体", "数据分析", "英语", "TikTok", "Instagram", "YouTube", "内容运营"],
        "publish_time": "2026-07",
        "source_site": "影石Insta360招聘官网",
        "source_link": "https://arashivision.jobs.feishu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "影石Insta360海外运营方向，英语流利，深圳。",
    },
    {
        "source_id": "CN-OP-009",
        "category": "运营",
        "title": "用户增长与运营实习生",
        "company": "特斯拉",
        "location": "重庆",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "150-250元/天",
        "education": "本科及以上，市场营销/传媒专业优先",
        "experience": "应届/实习",
        "responsibilities": "协助用户运营活动筹备与执行；负责新媒体平台（视频号、抖音等）内容策划与拍摄剪辑；线上平台运营与数据分析；参与用户增长策略制定与执行。",
        "requirements": "市场营销或传媒专业优先；需独立完成短视频策划拍摄与剪辑（FCPX/Pr/剪映）；实习4个月以上，每周≥4天。",
        "skills": ["用户运营", "新媒体运营", "短视频", "数据分析", "活动策划", "FCPX", "剪映"],
        "publish_time": "2026-07",
        "source_site": "全职网",
        "source_link": "https://www.quanzhi.com/job/6a61840962f6005b2b2aa00e",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "特斯拉重庆，用户增长方向，150-250元/天，需视频制作能力。",
    },
    {
        "source_id": "CN-OP-010",
        "category": "运营",
        "title": "实习运营助理",
        "company": "重庆旱獭信息技术",
        "location": "重庆",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "150-200元/天",
        "education": "本科在校生",
        "experience": "应届/实习",
        "responsibilities": "负责物联网SaaS产品全域运营；账号运维与内容运营；运营数据监控与复盘；内容选题与原创文案撰写；跟踪行业热点与竞品动态。",
        "requirements": "有独立站或社媒账号运营实操经验（无经验勿投）；具备基础数据整理与文案撰写能力；对物联网和SaaS领域有兴趣。",
        "skills": ["内容运营", "数据分析", "文案撰写", "社群运营", "竞品分析", "SaaS"],
        "publish_time": "2026-07",
        "source_site": "全职网",
        "source_link": "https://www.quanzhi.com/job/6a62066162f6005b2b2bb7fe",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "重庆旱獭信息，物联网SaaS运营，150-200元/天。",
    },
    {
        "source_id": "CN-OP-011",
        "category": "运营",
        "title": "运营类实习生（多方向）",
        "company": "字节跳动",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2027届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责平台内容审核、推荐与优化；参与用户增长活动策划与数据分析；协助产品功能日常运营；完成竞品分析与行业调研报告。",
        "requirements": "2027届本科及以上（2026届可投递全职）；每周≥4天，实习至少2个月；转正率55%。",
        "skills": ["内容运营", "用户运营", "数据分析", "活动策划", "竞品分析", "项目管理"],
        "publish_time": "2026-07",
        "source_site": "字节跳动招聘官网",
        "source_link": "https://jobs.bytedance.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "字节跳动运营实习，1000+Offer，转正率55%，面向2027届。",
    },
    {
        "source_id": "CN-OP-012",
        "category": "运营",
        "title": "内容运营实习生",
        "company": "搜狐",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "3K-3.6K/月",
        "education": "本科及以上，新闻、传播、广告、统计学类专业优先",
        "experience": "应届/实习",
        "responsibilities": "负责院线电影片花上传和内容管理；撰写公众号图文内容；协助视频剪辑和内容策划；参与内容数据分析和效果评估。",
        "requirements": "新闻、传播、广告、统计学类专业优先；需掌握PS、PR、剪映等工具；有一定的文字功底和审美能力。",
        "skills": ["内容运营", "视频剪辑", "文案撰写", "数据分析", "PS", "PR", "剪映", "公众号运营"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云/实习僧",
        "source_link": "https://league.rc114.com/Union/Position?jobId=571FB509-FDE1-4D14-89E0-4070A93B358F",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "搜狐内容运营，3K-3.6K/月，需PS/PR技能。",
    },
    {
        "source_id": "CN-OP-013",
        "category": "运营",
        "title": "新媒体运营实习生（雇主品牌）",
        "company": "特斯拉",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "6K-7.5K/月",
        "education": "本科及以上，影视、编导、数字媒体、传媒等相关专业",
        "experience": "应届/实习",
        "responsibilities": "负责雇主品牌短视频后期剪辑与内容编排；支持视频号、抖音、小红书等平台内容产出；参与内容策划和数据分析；推动雇主品牌传播效果提升。",
        "requirements": "影视、编导、数字媒体、视觉传达、传媒等相关专业；熟练使用FCPX/Pr/剪映；实习4个月以上，每周不少于4天。",
        "skills": ["新媒体运营", "视频剪辑", "内容策划", "数据分析", "FCPX", "PR", "剪映", "抖音", "小红书"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云/实习僧",
        "source_link": "https://league.rc114.com/Union/Position?jobId=0208A780-8457-4104-9030-17E9D08A07AB",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "特斯拉雇主品牌方向，6K-7.5K/月，需视频剪辑能力。",
    },
    {
        "source_id": "CN-OP-014",
        "category": "运营",
        "title": "新媒体运营实习生",
        "company": "深圳艾欧普特数字科技",
        "location": "昆明",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "4K-6K/月",
        "education": "2026届本科，专业不限",
        "experience": "应届/实习",
        "responsibilities": "负责小红书、抖音、视频号、公众号内容策划与日常运营；使用AI工具辅助内容生产和视频剪辑；跟踪内容数据并优化运营策略；参与品牌传播方案设计。",
        "requirements": "不限专业、不限经验，2026届毕业生优先；有社媒运营经验优先；对AI工具有一定了解；积极好学。",
        "skills": ["新媒体运营", "内容策划", "AI工具", "小红书", "抖音", "视频号", "公众号", "数据分析"],
        "publish_time": "2026-07",
        "source_site": "云南民大就业网",
        "source_link": "http://jyb.ynni.edu.cn/detail/job?id=3050041",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "深圳艾欧普特，AI+新媒体方向，4K-6K/月，不限专业。",
    },
    {
        "source_id": "CN-OP-015",
        "category": "运营",
        "title": "新媒体策划运营实习生",
        "company": "北京鼎帷管理顾问",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上，新媒体、传播学、传媒等相关专业",
        "experience": "应届/实习",
        "responsibilities": "负责新媒体平台内容策划与发布；协助视频剪辑和图文制作；进行内容数据分析和效果评估；参与品牌传播方案设计和执行。",
        "requirements": "新媒体、传播学、艺术设计、传媒等相关专业；一周至少4天，连续实习3个月以上；有视频剪辑和图文制作能力。",
        "skills": ["新媒体运营", "内容策划", "视频剪辑", "数据分析", "图文制作", "品牌传播"],
        "publish_time": "2026-07",
        "source_site": "国家大学生就业服务平台",
        "source_link": "https://ny.ncss.cn/student/jobs/CpAXvkJJbUcDw6bYjxwfNn/detail.html",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "北京鼎帷管理顾问，新媒体策划方向，招聘3人。",
    },
    {
        "source_id": "CN-OP-016",
        "category": "运营",
        "title": "运营实习生（内容方向）",
        "company": "成都海艺互娱",
        "location": "成都",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责游戏社区内容运营和用户互动；策划和执行内容营销方案；跟踪内容数据和用户反馈；参与海外内容运营和本地化。",
        "requirements": "对游戏和内容运营有热情；有社媒运营经验；有英语能力加分；2026届应届生及2027届实习生均可。",
        "skills": ["内容运营", "社群运营", "营销策划", "数据分析", "英语"],
        "publish_time": "2026-07",
        "source_site": "成都海艺互娱招聘官网",
        "source_link": "https://career.cic.tsinghua.edu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "成都海艺互娱，游戏内容运营方向，2026届。",
    },
    {
        "source_id": "CN-OP-017",
        "category": "运营",
        "title": "运营实习生（电商方向）",
        "company": "拼多多",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与电商平台日常运营工作；负责商品管理、活动策划和用户运营；通过数据分析推动运营策略优化；参与大促活动方案设计和执行。",
        "requirements": "对电商运营有热情；具备数据分析和活动策划能力；能承受较大工作强度；有电商运营实习经验优先。",
        "skills": ["电商运营", "数据分析", "活动策划", "用户运营", "商品管理", "Excel", "SQL"],
        "publish_time": "2026-07",
        "source_site": "拼多多校招官网",
        "source_link": "https://careers.pinduoduo.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "拼多多电商运营，2026届，数据分析方向。",
    },

    # ========================================================================
    # 算法/机器学习 (17 jobs)
    # ========================================================================
    {
        "source_id": "CN-ML-001",
        "category": "算法/机器学习",
        "title": "AI算法工程师/全栈工程师实习生",
        "company": "杭州遥望网络科技",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届全日制本科/硕士，2027届可投实习",
        "experience": "应届/实习",
        "responsibilities": "参与大模型、多模态、视频生成、NLP、直播推荐、AIGC、数字人、AI Agent等方向的项目研发；完成模型训练、微调和效果评估；参与AI产品从0到1的技术落地。",
        "requirements": "2026届本科/硕士应届生，2027届可投实习；熟悉Python和PyTorch/TensorFlow；了解Transformer、Diffusion等模型架构；有论文或竞赛经验优先。",
        "skills": ["Python", "PyTorch", "TensorFlow", "Transformer", "大模型", "AIGC", "NLP", "多模态"],
        "publish_time": "2026-07",
        "source_site": "清华就业信息网",
        "source_link": "https://career.cic.tsinghua.edu.cn/xsglxt/f/jyxt/anony/showZwxx?zpxxid=550009616",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "杭州遥望网络，AI方向全面（大模型/多模态/AIGC），招聘12人。",
    },
    {
        "source_id": "CN-ML-002",
        "category": "算法/机器学习",
        "title": "大模型算法工程师实习生",
        "company": "荣耀终端",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "硕士、博士",
        "experience": "应届/实习",
        "responsibilities": "参与LLM、VLM、VLA等大模型预训练、微调和强化学习研究；优化大模型推理性能和效率；探索多模态模型的新架构和训练方法。",
        "requirements": "硕士或博士学历；熟悉Python和PyTorch；有大模型预训练/微调/强化学习经验；可实习6个月以上优先。",
        "skills": ["Python", "PyTorch", "LLM", "VLM", "VLA", "强化学习", "模型训练", "推理优化"],
        "publish_time": "2026-07",
        "source_site": "荣耀招聘官网",
        "source_link": "https://www.honor.com/cn/career/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "荣耀终端，大模型方向，招聘20人，硕博。",
    },
    {
        "source_id": "CN-ML-003",
        "category": "算法/机器学习",
        "title": "算法工程师实习生（多模态内容理解）",
        "company": "淘天有限公司（阿里巴巴）",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "5K以上/月",
        "education": "硕士及以上，2026年11月1日以后毕业",
        "experience": "应届/实习",
        "responsibilities": "参与多模态内容理解和内容质量审核算法研发；使用大模型技术提升内容理解准确率；优化推荐系统中的内容画像和标签体系；参与模型训练、评估和上线部署。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有大模型训练/微调经验优先；NLP或计算机视觉方向优先。",
        "skills": ["Python", "PyTorch", "多模态", "大模型", "NLP", "计算机视觉", "推荐系统", "模型评估"],
        "publish_time": "2026-07",
        "source_site": "北京大学就业信息网",
        "source_link": "https://scc.pku.edu.cn/frontpage/pku/html/recruitmentinfoForm.html?positionDetailId=03885449fab8425384823fd2a2ab03e0",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "淘天T-StarLab实习，多模态方向，5K+/月。",
    },
    {
        "source_id": "CN-ML-004",
        "category": "算法/机器学习",
        "title": "算法工程师实习生（生成式AI方向）",
        "company": "鲲动利（杭州）智能科技",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "300元/天",
        "education": "硕士及以上，2026/2027届",
        "experience": "应届/实习",
        "responsibilities": "参与扩散模型、图像/视频生成等生成式AI算法研发；开发AI Agent工具和自动化工作流；进行模型训练、评估和优化。",
        "requirements": "硕士及以上（优秀本科生可考虑）；熟悉Python和PyTorch；有扩散模型或生成式AI项目经验；2026/2027届。",
        "skills": ["Python", "PyTorch", "扩散模型", "图像生成", "视频生成", "AI Agent", "模型训练"],
        "publish_time": "2026-07",
        "source_site": "中国地质大学就业网",
        "source_link": "https://cug.91wllm.cn/campus/view/id/1000834",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "鲲动利生成式AI方向，300元/天，2026/2027届，正式15-25K。",
    },
    {
        "source_id": "CN-ML-005",
        "category": "算法/机器学习",
        "title": "算法实习生（大模型方向）",
        "company": "腾讯",
        "location": "深圳",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026-2027届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与腾讯混元大模型研发，包括预训练、指令微调、RLHF和模型评估；优化大模型推理性能；探索多模态和Agent等前沿方向。",
        "requirements": "2026-2027届硕士及以上；熟悉Python和PyTorch；有大模型或NLP研究经验；有顶会论文优先。",
        "skills": ["Python", "PyTorch", "大模型", "NLP", "RLHF", "模型训练", "推理优化", "多模态"],
        "publish_time": "2026-07",
        "source_site": "腾讯校招官网",
        "source_link": "https://join.qq.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "腾讯混元大模型，2026-2027届硕博，AI岗位扩招30%。",
    },
    {
        "source_id": "CN-ML-006",
        "category": "算法/机器学习",
        "title": "算法实习生（大模型方向）",
        "company": "阿里巴巴",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与通义大模型研发和优化；负责模型训练、微调和效果评估；探索多模态、Agent和工具学习等前沿方向；推动大模型在电商场景的落地应用。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有大模型训练或NLP研究经验；有顶会论文优先。",
        "skills": ["Python", "PyTorch", "大模型", "NLP", "多模态", "Agent", "模型训练", "模型评估"],
        "publish_time": "2026-07",
        "source_site": "阿里巴巴校招官网",
        "source_link": "https://talent.alibaba.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "阿里通义大模型，2026届硕博，电商场景落地。",
    },
    {
        "source_id": "CN-ML-007",
        "category": "算法/机器学习",
        "title": "机器学习工程师实习生",
        "company": "浙江银泰百货",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "4K-9K/月",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "参与推荐、搜索和营销算法研发；探索大模型在零售场景的落地应用；开发AI创新产品和功能；进行模型训练、评估和线上部署。",
        "requirements": "2026届本科及以上；熟悉Python和PyTorch优先；了解Transformer、CNN、RNN等模型架构；有推荐系统经验优先。",
        "skills": ["Python", "PyTorch", "推荐系统", "大模型", "Transformer", "模型训练", "模型部署", "SQL"],
        "publish_time": "2026-07",
        "source_site": "浙江银泰招聘官网",
        "source_link": "https://www.zju.edu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "银泰百货机器学习方向，4K-9K/月，零售场景AI落地。",
    },
    {
        "source_id": "CN-ML-008",
        "category": "算法/机器学习",
        "title": "算法工程师实习生（具身智能方向）",
        "company": "杭州宇泛智能科技",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "12K以上/月",
        "education": "硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与具身智能VLA/VLN算法研发；进行大模型推理加速研究；开发多模态大模型微调和落地应用；探索强化学习在机器人领域的应用。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有机器人、强化学习或多模态经验优先。",
        "skills": ["Python", "PyTorch", "VLA", "VLM", "强化学习", "多模态", "模型训练", "推理优化", "机器人"],
        "publish_time": "2026-07",
        "source_site": "浙江大学就业网",
        "source_link": "https://www.career.zju.edu.cn/jyxt/sczp/zphgl/ckZphdwXq.zf?dwxxid=JG1453240",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "宇泛智能具身智能方向，12K+/月，方向前沿。",
    },
    {
        "source_id": "CN-ML-009",
        "category": "算法/机器学习",
        "title": "基座模型算法实习生（生命科学方向）",
        "company": "上海人工智能实验室",
        "location": "上海",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与生命科学领域基座大模型研发；进行多模态（文本、结构、时序数据）融合研究；优化大模型训练方法；推动AI在生命科学领域的应用。",
        "requirements": "可实习3个月及以上；有LLM或多模态模型研究经验优先；熟悉Python和PyTorch；有生物信息学背景加分。",
        "skills": ["Python", "PyTorch", "大模型", "多模态", "LLM", "模型训练", "生物信息学"],
        "publish_time": "2026-07",
        "source_site": "上海人工智能实验室官网",
        "source_link": "https://www.shlab.org.cn/joinus/detail/7654905967037565222?mode=campus",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "上海AI Lab，基座模型方向，生命科学跨学科。",
    },
    {
        "source_id": "CN-ML-010",
        "category": "算法/机器学习",
        "title": "算法实习生（NLP方向）",
        "company": "百度",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与百度文心大模型NLP方向研发；负责文本生成、理解和对话系统的算法优化；进行模型训练、评估和上线部署；跟踪NLP前沿技术进展。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有NLP或大模型研究经验；有顶会论文优先。",
        "skills": ["Python", "PyTorch", "NLP", "大模型", "文本生成", "对话系统", "模型训练", "模型部署"],
        "publish_time": "2026-07",
        "source_site": "百度校招官网",
        "source_link": "https://talent.baidu.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "百度文心大模型NLP方向，2026届硕博。",
    },
    {
        "source_id": "CN-ML-011",
        "category": "算法/机器学习",
        "title": "算法实习生（推荐系统方向）",
        "company": "快手",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与快手推荐系统算法研发；优化短视频推荐和广告投放模型；进行大规模数据处理和特征工程；进行A/B实验设计和效果评估。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有推荐系统或机器学习项目经验；了解大规模数据处理。",
        "skills": ["Python", "PyTorch", "推荐系统", "机器学习", "特征工程", "A/B测试", "数据处理", "SQL"],
        "publish_time": "2026-07",
        "source_site": "快手校招官网",
        "source_link": "https://campus.kuaishou.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "快手推荐系统方向，2026届硕博，大规模数据处理。",
    },
    {
        "source_id": "CN-ML-012",
        "category": "算法/机器学习",
        "title": "算法实习生（计算机视觉方向）",
        "company": "字节跳动",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与抖音/剪映等产品中计算机视觉算法研发；负责图像/视频理解、生成和增强等方向；进行模型训练、优化和移动端部署。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有计算机视觉项目经验；有移动端模型部署经验优先。",
        "skills": ["Python", "PyTorch", "计算机视觉", "图像处理", "模型训练", "模型部署", "深度学习"],
        "publish_time": "2026-07",
        "source_site": "字节跳动招聘官网",
        "source_link": "https://jobs.bytedance.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "字节跳动CV方向，抖音/剪映产品，2026届硕博。",
    },
    {
        "source_id": "CN-ML-013",
        "category": "算法/机器学习",
        "title": "算法实习生（搜索方向）",
        "company": "美团",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与美团搜索和推荐算法研发；优化搜索结果相关性、排序和个性化推荐；进行大规模数据分析和模型训练；推动搜索体验提升。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有搜索、推荐或NLP项目经验；了解大规模机器学习系统。",
        "skills": ["Python", "PyTorch", "搜索算法", "推荐系统", "NLP", "机器学习", "数据处理"],
        "publish_time": "2026-07",
        "source_site": "美团校招官网",
        "source_link": "https://campus.meituan.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "美团搜索方向，2026届硕博，大规模机器学习。",
    },
    {
        "source_id": "CN-ML-014",
        "category": "算法/机器学习",
        "title": "算法实习生（风控方向）",
        "company": "蚂蚁集团",
        "location": "杭州",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与蚂蚁集团风控算法研发；构建反欺诈、信用评估和风险预警模型；进行大规模数据分析和特征工程；推动模型在金融场景的落地应用。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch/TensorFlow；有机器学习或数据挖掘项目经验；对金融风控有兴趣。",
        "skills": ["Python", "PyTorch", "TensorFlow", "机器学习", "数据挖掘", "特征工程", "风控模型", "SQL"],
        "publish_time": "2026-07",
        "source_site": "蚂蚁集团校招官网",
        "source_link": "https://talent.antgroup.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "蚂蚁集团风控方向，2026届硕博，金融AI。",
    },
    {
        "source_id": "CN-ML-015",
        "category": "算法/机器学习",
        "title": "算法实习生（自动驾驶感知方向）",
        "company": "滴滴",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与滴滴自动驾驶感知算法研发；负责激光雷达/视觉/多模态感知模型训练和优化；进行大规模数据标注和处理；推动算法在真实路测场景中的验证。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有计算机视觉或点云处理经验；了解自动驾驶感知系统优先。",
        "skills": ["Python", "PyTorch", "计算机视觉", "点云处理", "模型训练", "深度学习", "自动驾驶"],
        "publish_time": "2026-07",
        "source_site": "滴滴校招官网",
        "source_link": "https://campus.didiglobal.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "滴滴自动驾驶感知方向，2026届硕博。",
    },
    {
        "source_id": "CN-ML-016",
        "category": "算法/机器学习",
        "title": "算法实习生（语音方向）",
        "company": "小米",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与小米小爱同学语音算法研发；负责语音识别、语音合成和声纹识别模型训练和优化；推动语音算法在IoT设备上的落地部署。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有语音识别或语音合成项目经验；了解模型压缩和推理优化优先。",
        "skills": ["Python", "PyTorch", "语音识别", "语音合成", "模型训练", "模型压缩", "深度学习"],
        "publish_time": "2026-07",
        "source_site": "小米校招官网",
        "source_link": "https://hr.xiaomi.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "小米小爱同学语音方向，2026届硕博。",
    },
    {
        "source_id": "CN-ML-017",
        "category": "算法/机器学习",
        "title": "算法实习生（数据科学方向）",
        "company": "京东",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届硕士及以上",
        "experience": "应届/实习",
        "responsibilities": "参与京东电商数据科学项目；负责用户画像、销量预测和定价优化等算法研发；进行大规模数据分析和模型训练；推动算法在电商场景的落地。",
        "requirements": "硕士及以上学历；熟悉Python和PyTorch；有数据挖掘或机器学习项目经验；了解统计学和A/B实验设计。",
        "skills": ["Python", "PyTorch", "数据挖掘", "机器学习", "数据分析", "A/B测试", "SQL", "统计学"],
        "publish_time": "2026-07",
        "source_site": "京东校招官网",
        "source_link": "https://campus.jd.com/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "京东数据科学方向，2026届硕博，电商场景AI。",
    },

    # ========================================================================
    # 数字媒体/内容 (16 jobs)
    # ========================================================================
    {
        "source_id": "CN-DM-001",
        "category": "数字媒体/内容",
        "title": "视频剪辑实习生",
        "company": "中国建筑出版传媒",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上，影视剪辑、数字媒体、新媒体、视觉传达相关专业",
        "experience": "应届/实习",
        "responsibilities": "负责建筑类图书带货短视频剪辑与制作；配合运营团队完成视频内容策划和创意执行；参与视频素材管理和后期包装。",
        "requirements": "影视剪辑、数字媒体、新媒体、视觉传达相关专业优先；熟练使用剪映、PR等剪辑工具；需附作品集。",
        "skills": ["视频剪辑", "剪映", "PR", "数字媒体", "短视频", "内容策划", "后期包装"],
        "publish_time": "2026-07",
        "source_site": "大连理工就业信息网",
        "source_link": "http://pjcareer.dlut.edu.cn/info/1091/44062.htm",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "中国建筑出版传媒，招聘20人，数字媒体方向，需附作品集。",
    },
    {
        "source_id": "CN-DM-002",
        "category": "数字媒体/内容",
        "title": "新媒体运营实习生",
        "company": "中国建筑出版传媒",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上，网络与新媒体、新闻传播、广告等专业优先",
        "experience": "应届/实习",
        "responsibilities": "负责公众号、抖音、小红书等平台运营；进行选题策划和图文笔记撰写；跟踪内容数据和用户互动；参与品牌传播方案设计。",
        "requirements": "网络与新媒体、新闻传播、广告等专业优先；有新媒体运营经验；有图文创作能力。",
        "skills": ["新媒体运营", "内容策划", "文案撰写", "公众号运营", "抖音", "小红书", "数据分析"],
        "publish_time": "2026-07",
        "source_site": "大连理工就业信息网",
        "source_link": "http://pjcareer.dlut.edu.cn/info/1091/44062.htm",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "中国建筑出版传媒，招聘20人，新媒体方向。",
    },
    {
        "source_id": "CN-DM-003",
        "category": "数字媒体/内容",
        "title": "AIGC内容运营实习生",
        "company": "美图公司",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "5.4K-6K/月",
        "education": "本科及以上，数字媒体、影视制作、动画、视觉传达相关专业优先",
        "experience": "应届/实习",
        "responsibilities": "使用可灵、海螺等AI工具创作AIGC视频内容；负责视频后期制作和效果优化；参与AI内容策略设计和效果评估；跟踪AIGC行业前沿工具和技术。",
        "requirements": "数字媒体、影视制作、动画、视觉传达等相关专业优先；有扎实的视频后期功底；对AI视频生成工具有使用经验优先。",
        "skills": ["视频剪辑", "AIGC", "AI工具", "后期制作", "数字媒体", "内容策略", "影视制作"],
        "publish_time": "2026-07",
        "source_site": "天府招聘云/实习僧",
        "source_link": "https://league.rc114.com/Union/Position?jobId=0D146F83-7213-4529-BCCA-22FF7173372F",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "美图AIGC方向，5.4K-6K/月，AI工具创作。",
    },
    {
        "source_id": "CN-DM-004",
        "category": "数字媒体/内容",
        "title": "短视频运营实习生",
        "company": "新经典文化",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责图书类抖音、小红书、视频号短视频发布与运营；使用剪映、PR、PS进行视频制作和图片处理；跟踪视频数据并优化内容策略。",
        "requirements": "熟练使用剪映、PR、PS；有短视频运营经验优先；对图书和文化内容有兴趣；每周到岗至少3天。",
        "skills": ["短视频", "剪映", "PR", "PS", "抖音", "小红书", "视频号", "内容运营"],
        "publish_time": "2026-07",
        "source_site": "北京大学就业信息网",
        "source_link": "https://scc.pku.edu.cn/frontpage/pku/html/recruitmentinfoForm.html?positionDetailId=716efab59ffa41d399f5bc36ca116c1e",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "新经典文化，图书短视频方向，需PR/PS/剪映技能。",
    },
    {
        "source_id": "CN-DM-005",
        "category": "数字媒体/内容",
        "title": "创意视频实习生",
        "company": "新经典文化",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责童书短视频策划、拍摄与后期制作；需真人出镜讲解童书内容；具备编导和剪辑能力；参与内容创意方案设计。",
        "requirements": "需真人出镜，形象良好；具备编导和剪辑能力；有短视频创作经验；对童书和亲子内容有兴趣。",
        "skills": ["视频拍摄", "视频剪辑", "编导", "内容策划", "出镜表演", "PR", "剪映"],
        "publish_time": "2026-07",
        "source_site": "北京大学就业信息网",
        "source_link": "https://scc.pku.edu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "新经典文化童书方向，创意视频，需真人出镜。",
    },
    {
        "source_id": "CN-DM-006",
        "category": "数字媒体/内容",
        "title": "短视频剪辑实习生",
        "company": "成都海艺互娱",
        "location": "成都",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责游戏类短视频剪辑与制作；配合运营团队完成内容营销方案执行；参与视频创意策划和效果优化。",
        "requirements": "2026届应届生；熟练使用剪映、PR等剪辑工具；有游戏视频制作经验优先；福利优厚，扁平化管理。",
        "skills": ["视频剪辑", "剪映", "PR", "短视频", "内容营销", "游戏"],
        "publish_time": "2026-07",
        "source_site": "清华就业信息网",
        "source_link": "https://career.cic.tsinghua.edu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "成都海艺互娱，游戏短视频方向，2026届春招。",
    },
    {
        "source_id": "CN-DM-007",
        "category": "数字媒体/内容",
        "title": "内容营销实习生",
        "company": "成都海艺互娱",
        "location": "成都",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责游戏产品的内容营销方案策划与执行；管理社交媒体账号和内容发布；跟踪内容数据和用户反馈；参与品牌传播和用户增长活动。",
        "requirements": "2026届应届生；有内容营销或社媒运营经验；对游戏行业有热情；有英语能力加分。",
        "skills": ["内容营销", "社交媒体", "数据分析", "文案撰写", "品牌传播", "英语"],
        "publish_time": "2026-07",
        "source_site": "清华就业信息网",
        "source_link": "https://career.cic.tsinghua.edu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "成都海艺互娱，内容营销方向，2026届。",
    },
    {
        "source_id": "CN-DM-008",
        "category": "数字媒体/内容",
        "title": "短视频营销实习生（童书方向）",
        "company": "新经典文化",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责童书类短视频策划、拍摄与后期制作；配合营销团队完成图书推广方案执行；参与KOL合作和内容分发。",
        "requirements": "有短视频创作和剪辑经验；对童书和亲子内容有兴趣；熟练使用剪映、PR等工具；每周到岗至少3天。",
        "skills": ["短视频", "视频拍摄", "视频剪辑", "PR", "剪映", "内容策划", "营销推广"],
        "publish_time": "2026-07",
        "source_site": "北京大学就业信息网",
        "source_link": "https://scc.pku.edu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "新经典文化童书营销方向，短视频策划拍摄剪辑。",
    },
    {
        "source_id": "CN-DM-009",
        "category": "数字媒体/内容",
        "title": "拍剪实习生",
        "company": "上海泛猩文化传媒成都分公司",
        "location": "成都",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上，数字媒体艺术、网络与新媒体等专业",
        "experience": "应届/实习",
        "responsibilities": "负责短视频拍摄与剪辑；运营和管理视频账号；参与内容创意和选题策划。",
        "requirements": "数字媒体艺术、网络与新媒体等专业对口；有视频拍摄和剪辑能力；连续实习3个月以上。",
        "skills": ["视频拍摄", "视频剪辑", "短视频", "内容策划", "数字媒体", "账号运营"],
        "publish_time": "2026-07",
        "source_site": "国家大学生就业服务平台",
        "source_link": "https://ny.ncss.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "上海泛猩成都分公司，数字媒体艺术专业对口。",
    },
    {
        "source_id": "CN-DM-010",
        "category": "数字媒体/内容",
        "title": "运营实习生（笔记宣发方向）",
        "company": "上海泛猩文化传媒成都分公司",
        "location": "成都",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "负责小红书等平台笔记宣发和内容运营；跟踪内容数据并优化发布策略；协助内容策划和选题设计。",
        "requirements": "网感好，了解小红书等内容平台；有内容创作经验；连续实习3个月以上。",
        "skills": ["内容运营", "小红书", "数据分析", "文案撰写", "内容策划"],
        "publish_time": "2026-07",
        "source_site": "国家大学生就业服务平台",
        "source_link": "https://ny.ncss.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "上海泛猩成都分公司，小红书笔记宣发方向。",
    },
    {
        "source_id": "CN-DM-011",
        "category": "数字媒体/内容",
        "title": "新媒体运营实习生",
        "company": "新东方教育科技集团",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上，专业不限",
        "experience": "应届/实习",
        "responsibilities": "负责新东方旗下新媒体账号运营；策划和发布教育类图文和短视频内容；跟踪内容数据和用户增长；参与品牌传播和活动推广。",
        "requirements": "专业不限；有新媒体运营经验；有图文创作和短视频制作能力；对教育行业有热情。",
        "skills": ["新媒体运营", "内容策划", "短视频", "文案撰写", "数据分析", "教育行业"],
        "publish_time": "2026-07",
        "source_site": "新东方招聘官网",
        "source_link": "https://zhaopin.xdf.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "新东方教育，新媒体方向，专业不限，全国多城市。",
    },
    {
        "source_id": "CN-DM-012",
        "category": "数字媒体/内容",
        "title": "直播运营实习生",
        "company": "新东方教育科技集团",
        "location": "北京",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上，专业不限",
        "experience": "应届/实习",
        "responsibilities": "负责教育类直播间的运营和维护；配合主播完成课程推广和用户互动；进行直播数据分析和效果优化；参与直播脚本策划和活动设计。",
        "requirements": "专业不限；对直播行业有兴趣；有直播运营或主播经验优先；沟通表达能力强。",
        "skills": ["直播运营", "数据分析", "脚本策划", "活动策划", "用户互动"],
        "publish_time": "2026-07",
        "source_site": "新东方招聘官网",
        "source_link": "https://zhaopin.xdf.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "新东方教育，直播运营方向，专业不限。",
    },
    {
        "source_id": "CN-DM-013",
        "category": "数字媒体/内容",
        "title": "内容运营实习生（海外方向）",
        "company": "成都海艺互娱",
        "location": "成都",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "2026届本科及以上，英语流利",
        "experience": "应届/实习",
        "responsibilities": "负责海外游戏社区内容运营和用户互动；策划和执行海外内容营销方案；进行内容数据分析和本地化优化。",
        "requirements": "2026届应届生；英语流利，能进行英文内容创作；有海外社媒运营经验优先；对游戏行业有热情。",
        "skills": ["内容运营", "英语", "社交媒体", "数据分析", "本地化", "游戏"],
        "publish_time": "2026-07",
        "source_site": "清华就业信息网",
        "source_link": "https://career.cic.tsinghua.edu.cn/",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "成都海艺互娱海外内容方向，英语流利，2026届。",
    },
    {
        "source_id": "CN-DM-014",
        "category": "数字媒体/内容",
        "title": "SEO和GEO内容实习生",
        "company": "Back Market",
        "location": "未标注（海外远程）",
        "employment_type": "实习",
        "workplace_type": "远程",
        "salary_range": "未标注",
        "education": "在读学生或毕业阶段",
        "experience": "应届/实习",
        "responsibilities": "制作SEO/GEO优化文章；使用CMS发布和管理内容；支持国际内容策略执行；分析搜索和AI可见性数据。",
        "requirements": "德语和英语流利；具备写作、数据分析、SEO工具使用能力；6个月实习期。",
        "skills": ["SEO", "GEO", "内容写作", "CMS", "数据分析", "英语", "德语", "AI内容"],
        "publish_time": "2026-07",
        "source_site": "Ashby",
        "source_link": "https://jobs.ashbyhq.com/backmarket/07efbbd2-9cca-4f00-a9fc-2fa7c9d71a75",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "Back Market SEO/GEO方向，德语英语双语，6个月实习。",
    },
    {
        "source_id": "CN-DM-015",
        "category": "数字媒体/内容",
        "title": "内容实习生",
        "company": "Revel Robotics",
        "location": "未标注（海外）",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "本科及以上",
        "experience": "应届/实习",
        "responsibilities": "协助拍摄和剪辑视频内容；组织和管理数字素材；提供内容制作支持；参与创意策划。",
        "requirements": "有组织性，主动可靠；有基础内容或视频经验；掌握基础剪辑和社媒能力。",
        "skills": ["视频拍摄", "视频剪辑", "素材管理", "内容制作", "社交媒体", "数字媒体"],
        "publish_time": "未标注",
        "source_site": "Ashby",
        "source_link": "https://jobs.ashbyhq.com/revelrobotics/b390d41b-b8ff-4fc6-a04a-b82105922d1b",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "Revel Robotics，数字媒体内容方向，海外实习。",
    },
    {
        "source_id": "CN-DM-016",
        "category": "数字媒体/内容",
        "title": "社交媒体与视频内容实习生",
        "company": "Valency Systems",
        "location": "未标注（海外）",
        "employment_type": "实习",
        "workplace_type": "现场",
        "salary_range": "未标注",
        "education": "技术、研究或相关背景优先",
        "experience": "应届/实习",
        "responsibilities": "制作技术视频演示；维护LinkedIn、YouTube、BlueSky内容日历；分发内容并追踪互动数据；参与内容策略优化。",
        "requirements": "有视频剪辑和专业社交平台经验；理解研究或技术受众；能独立维护内容节奏。",
        "skills": ["短视频", "视频剪辑", "内容日历", "LinkedIn", "YouTube", "数据分析", "技术写作"],
        "publish_time": "Summer 2026",
        "source_site": "Ashby",
        "source_link": "https://jobs.ashbyhq.com/valency/e9861e9b-585e-4c53-85dd-92d067748ad1",
        "collected_at": COLLECTED_AT,
        "status": "pending",
        "audit_comment": "Valency Systems，技术视频内容方向，海外实习。",
    },
]


# ============================================================================
# Script entry point
# ============================================================================

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Generate 100 Chinese job listings")
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help=f"Output JSONL path (default: {OUTPUT_PATH})",
    )
    args = parser.parse_args()

    records = JOBS

    # Validate
    errors = 0
    for i, record in enumerate(records):
        required = [
            "source_id", "category", "title", "company", "location",
            "employment_type", "workplace_type", "salary_range", "education",
            "experience", "responsibilities", "requirements", "skills",
            "publish_time", "source_site", "source_link", "collected_at",
            "status", "audit_comment",
        ]
        for field in required:
            if field not in record or not record[field]:
                print(f"ERROR record #{i}: missing field '{field}'")
                errors += 1

    if errors:
        print(f"Found {errors} validation errors. Aborting.")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    # Summary
    categories = {}
    for record in records:
        cat = record["category"]
        categories[cat] = categories.get(cat, 0) + 1

    print(f"Generated {len(records)} Chinese job records")
    print(f"Output: {args.output}")
    print("\nCategory distribution:")
    for cat, count in sorted(categories.items()):
        print(f"  {cat}: {count}")
    print(f"\nStatus: all records set to 'pending' (awaiting human audit)")


if __name__ == "__main__":
    main()
